# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recname', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('idf', models.BigIntegerField(default=0)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
