# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-26 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_auto_20160626_0832'),
    ]

    operations = [
    ]
