# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0003_auto_20160626_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
                ('scount', models.BigIntegerField(default=0)),
            ],
        ),
    ]
